# Generated by Django 5.1.5 on 2026-08-19 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('source_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('respondent_count', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Column order in the source file.')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('categorical', 'Categorical'), ('ordinal', 'Ordinal'), ('numeric', 'Numeric'), ('free_text', 'Free text')], max_length=20)),
                ('distinct_values', models.PositiveIntegerField(default=0)),
                ('missing_count', models.PositiveIntegerField(default=0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.dataset')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_key', models.CharField(max_length=64)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.dataset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='surveys.survey'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('dataset', 'position'), name='unique_question_position_per_dataset'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['dataset', 'question'], name='response_dataset_question'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['dataset', 'respondent_key'], name='response_dataset_person'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('question', 'respondent_key'), name='unique_answer_per_question_and_respondent'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_survey_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('survey', 'version'), name='unique_version_per_survey'),
        ),
    ]
